### ISSUE TITLE
Interchain Security

### ISSUE THREAD

**Issue by faddat** [eve-network/eve#123]
Let's integrate support for github.com/cosmos/interchain-security

this may require upgrading ics to ibc v8

**Comment by hoank101** [comment]
need upgrade interchain-security first https://github.com/notional-labs/interchain-security/tree/faddat/ibc8

**Comment by faddat** [comment]
sad but true... also that branch is likely out of date

**Comment by hoank101** [comment]
yeah, not easy for interchain security upgrade, many change code base

**Comment by hoank101** [comment]
will work on this issues -> https://github.com/cosmos/interchain-security/issues/1246

**Comment by faddat** [comment]
Yeah I think that we probably shouldn't use my old PR. It's probably something we have to do from the ground up.

**Comment by hoank101** [comment]
https://github.com/eve-network/eve/pull/170
