### ISSUE TITLE
Consensus failed when start local local node

### ISSUE THREAD

**Issue by hoank101** [eve-network/eve#160]
`./scripts/start_local_node.sh`

<img width="2202" alt="Screenshot 2024-03-11 at 10 36 29" src="https://github.com/eve-network/eve/assets/153518241/dac0fe14-e568-43d7-b5d1-9dab33f854e1">

**Comment by faddat** [comment]
Disabling ics fixed this?

**Comment by hoank101** [comment]
yes sir, have some issues when enable ICS, currently not stable, i need time to check

**Comment by hoank101** [comment]
fixed
