### ISSUE TITLE
tokenfactory miss anotation

### ISSUE THREAD

**Issue by hoank101** [eve-network/eve#173]
when start chain, testing have issues related tokenfactory
`service tokenfactory.v1beta1.Msg does not have cosmos.msg.v1.service proto annotation
`
<img width="1116" alt="Screenshot 2024-03-18 at 21 15 22" src="https://github.com/eve-network/eve/assets/153518241/e89834dc-df99-457f-86de-16dd30f10eca">

**Comment by faddat** [comment]
this is probably an issue in the token factory v50 upgrade work.
