### ISSUE TITLE
Epochs

### ISSUE THREAD

**Issue by faddat** [eve-network/eve#23]
Well, it is likely reasonable that the osmosis epoch module makes sense for this and they just made it importable but it isn't 46ified. 

Propose we 46ify it here and let folks import right?

**Comment by Reecepbcups** [comment]
not sure this makes sense if we take the emoney approach w/ forked modules for staking & distribution anyways

**Comment by faddat** [comment]
emoney approach makes it necessary imo.  Fire once an hour.
