### ISSUE TITLE
Airdrop

### ISSUE THREAD

**Issue by Reecepbcups** [eve-network/eve#5]
For:
- most for contributors [includign CosmosSDK, gaia, writing code]
- select chains?
- What about gov participation?

NOTE: design airdrop per section, output to .sh file with add-genesis-account --append is used.

Requirements:
- state exports of chains
- PLEASE NO EVM CHAINS! (Only 118)

I can do this, just need to know:
- token->eve convert rate
- Any other airdrop considerations / logic wanted

How to airdrop to contributors:
- github crawl commits from main repos
- get their github username / uuid
- webapp sign in, get their name
- connect keplr
- deposit eve on a per commit basis / pr / # of lines of code? 

Contributor Airdrop Core/Chains:
[@cosmossdk](https://twitter.com/cosmossdk)
[@Tendermint_Core](https://twitter.com/Tendermint_Core)
[@cosmosibc](https://twitter.com/cosmosibc)
tmdb
cosmos-db
[@CosmWasm](https://twitter.com/CosmWasm)
[@CockroachDB](https://twitter.com/CockroachDB)

[@osmosiszone](https://twitter.com/osmosiszone)
[@cosmoshub](https://twitter.com/cosmoshub)
[@akashnet_](https://twitter.com/akashnet_)
[@StargazeZone](https://twitter.com/StargazeZone)
[@JunoNetwork](https://twitter.com/JunoNetwork)
[@DA0_DA0](https://twitter.com/DA0_DA0)

**Comment by Nharto** [comment]
Done

**Comment by Reecepbcups** [comment]
> Done 

Where? PR?
